global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # =========================
  # MAHI BACKEND (FastAPI)
  # =========================
  - job_name: "mahi-backend"
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: mahi-backend
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: mahi-ai-canary
      - action: keep
        source_labels: [__meta_kubernetes_service_port_number]
        regex: "8000"

  # =========================
  # KUBE STATE METRICS
  # =========================
  - job_name: "kube-state-metrics"
    static_configs:
      - targets:
          - kube-state-metrics.monitoring.svc.cluster.local:8080
