apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: "node-exporter"
        static_configs:
          - targets:
              - node-exporter.monitoring.svc.cluster.local:9100

      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              - kube-state-metrics.kube-system.svc.cluster.local:8080

      - job_name: "mahi-backend"
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: mahi-backend
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: mahi-ai-canary
