apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "kubernetes-services"
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            regex: "true"
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
            target_label: __address__
            regex: (.+)
            replacement: $1

      - job_name: "kube-state-metrics"
        static_configs:
          - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]