apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahi-backend
spec:
  replicas: 1   # Canary
  template:
    spec:
      containers:
        - name: backend
          image: YOUR_DOCKER_USERNAME/mahi-backend:v1.0.2
