apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahi-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          image: rameshcloud/mahi-backend:IMAGE_TAG

