apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: rameshcloud/mahi-backend
    newTag: v2.2.3

  - name: rameshcloud/mahi-frontend
    newTag: v2.2.3
