apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahi-backend
  template:
    metadata:
      labels:
        app: mahi-backend
    spec:
      containers:
        - name: backend
          image: rameshcloud/mahi-backend
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_NAME
              value: "phi"
            - name: OLLAMA_URL
              value: "http://ollama:11434/api/generate"

